"""added entity_id FK to Post model

Revision ID: fcc028347e4a
Revises: bdee7da66470
Create Date: 2018-10-04 15:58:43.379308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc028347e4a'
down_revision = 'bdee7da66470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'base_entity', ['entity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'entity_id')
    # ### end Alembic commands ###
